application_order_cart:
    path:     /cart
    defaults: { _controller: "ApplicationShopBundle:Order:cart" }
    
application_order_checkout:
    path:     /checkout
    defaults: { _controller: "ApplicationShopBundle:Order:checkout" }
    
application_order_checkout_create:
    path:     /create
    defaults: { _controller: "ApplicationShopBundle:Order:create" }
    requirements: { _method: post }
